# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
    emptymod:
        container_name: emptymod
        image: ${REGISTRY:-ghcr.io/imesense}/mcforge1.12-emptymod:${IMAGE_TAG:-latest}
        platform: linux/amd64
        environment:
            - EULA=${EULA:-false}
        ports:
            - "${SERVER_PORT:-25565}:25565"
        volumes:
            - ${VOLUME_WORLD:-../../world}:/app/world
            - ${VOLUME_CONFIG:-../../config}:/app/config
            - ${VOLUME_REPORTS:-../../crash-reports}:/app/crash-reports
            - ${VOLUME_PROPERTIES:-../../server.properties}:/app/server.properties
        networks:
            - emptymod
        restart: unless-stopped

networks:
    emptymod:
        name: emptymod
        driver: bridge
