# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
    # Empty mod server
    boilerplatemcforge-server:
        container_name: boilerplatemcforge-server
        image: ${REGISTRY:-ghcr.io/imesense}/mcforge1.12.2-modification-boilerplate-server:${IMAGE_TAG:-latest}
        platform: linux/amd64
        environment:
            - EULA=${EULA:-false}
        ports:
            - "${SERVER_PORT:-25565}:25565"
        volumes:
            - ${VOLUME_WORLD:-../../world}:/app/world
            - ${VOLUME_CONFIG:-../../config}:/app/config
            - ${VOLUME_REPORTS:-../../crash-reports}:/app/crash-reports
            - ${VOLUME_PROPERTIES:-../../server.properties}:/app/server.properties
        networks:
            - boilerplatemcforge-server
        restart: unless-stopped

networks:
    boilerplatemcforge-server:
        name: boilerplatemcforge-server
        driver: bridge
