plugins {
    id 'java'

    id 'eclipse'
    id 'idea'

    alias libs.plugins.minecraftforge.gradle
    alias libs.plugins.spongepowered.mixin
    alias libs.plugins.gofancy.fancygradle
}

repositories {
    flatDir {
        dirs 'lib'
    }
    flatDir {
        dirs 'libs'
    }
    maven {
        url "file://${rootDir}/dep/maven-packages-store/src/www.cursemaven.com"
    }
    maven {
        url "file://${rootDir}/dep/maven-packages-store/src/maven.su5ed.dev/releases"
    }
    maven {
        url 'https://maven.minecraftforge.net'
    }
}

apply plugin: 'maven-publish'

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

// File metadata
version = '1.12.2-0.2'
group = 'org.imesense'
base.archivesName = 'BoilerplateMcforge'

// Java version
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

// Compile options
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:-options']
}

minecraft {
    // Mappings settings of Minecraft
    mappings channel: 'stable', version: libs.versions.minecraft.mappings

    // Default run configurations
    runs {
        client {
            args "--username=InDev"

            jvmArg "-Dfml.coreMods.load=org.imesense.boilerplate.mcforge.plugin.LoadingPlugin"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'
        }

        server {
            jvmArg "-Dfml.coreMods.load=org.imesense.boilerplate.mcforge.plugin.LoadingPlugin"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'
        }
    }
}

mixin {
    add sourceSets.main, 'mixins.boilerplatemcforge.refmap.json'
}

dependencies {
    // Specify the version of Minecraft to use
    minecraft libs.minecraftforge

    // Mixins
    compileOnly libs.mixin
    annotationProcessor variantOf(libs.mixin) {
        classifier('processor')
    }
    compileOnly libs.mixinextras
    annotationProcessor libs.mixinextras
    implementation fg.deobf(libs.fermiumbooter)

    // Just Enough Item
    implementation fg.deobf(libs.jei)

    // Lombok
    //compileOnly 'org.projectlombok:lombok:1.18.30'
    //annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // Byte Buddy
    testImplementation(libs.bytebuddy) {
        transitive = false
    }

    // JUnit
    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine

    // Mockito
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.mockito.inline

    // Mixins
    testImplementation libs.mixin
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"
    }
}

fancyGradle {
    patches {
        resources
        coremods
        asm
        mergetool
    }
}

// Get properties into the manifest for reading by the runtime
jar {
    manifest {
        def attribute = [:]
        attribute['Specification-Title'] = 'boilerplatemcforge'
        attribute['Specification-Vendor'] = 'imesense'
        attribute['Specification-Version'] = '1'
        attribute['Implementation-Title'] = project.name
        attribute['Implementation-Vendor'] = 'imesense'
        attribute['Implementation-Version'] = '${version}'
        attribute['Implementation-Timestamp'] = new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        attribute['FMLCorePlugin'] = 'org.imesense.boilerplate.mcforge.plugin.LoadingPlugin'
        attribute['FMLCorePluginContainsFMLMod'] = 'true'
        attribute['TweakClass'] = 'org.spongepowered.asm.launch.MixinTweaker'
        attribute['ForceLoadAsMod'] = "true"

        def currentTasks = gradle.startParameter.taskNames
        if (currentTasks[0] == 'build' || currentTasks[0] == 'assemble') {
            attribute['ForceLoadAsMod'] = "true"
        }

        attributes(attribute)
    }
}

// Preferred method to reobfuscate JAR file
jar.finalizedBy('reobfJar')

// Build sources task
tasks.register('sourcesJar', Jar) {
    dependsOn processResources
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

// Build documentation task
tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    from "$buildDir/docs/javadoc"
    archiveClassifier = 'javadoc'
}

// Delay the obfuscation
//publish.dependsOn('reobfJar')

// Set publish settings
publishing {
    publications {
        mavenJava(MavenPublication) {
            // Redefine output name
            artifactId = "boilerplatemcforge"

            artifact jar
            artifact sourcesJar
            artifact javadocJar

            // Add dependencies to manifest
            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')
                configurations.runtimeClasspath.allDependencies.each { dep ->
                    if (dep.group != null && dep.name != null) {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', dep.group)
                        dependencyNode.appendNode('artifactId', dep.name)
                        dependencyNode.appendNode('version', dep.version)
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// Map of dependency file name patterns to target renamed JAR names.
def dependencies = [:]
dependencies['fermiumbooter'] = '`FermiumBooter-1.4.1.jar'
//dependencies['jei'] = 'jei_1.12.2-4.16.1.1013.jar'

tasks.register('copyDependencies', Copy) {
    from configurations.runtimeClasspath.filter { file ->
        dependencies.keySet().any { pattern ->
            file.name.toLowerCase().contains(pattern)
        }
    }
    into 'run/mods'
    dependencies.each { pattern, targetName ->
        filesMatching("**/*${pattern}*.jar") {
            it.name = targetName
        }
    }
}

tasks.register('prepareAssets', Copy) {
    from sourceSets.main.resources
    into layout.buildDirectory.dir('classes/java/main')
}

tasks.named('classes') {
    dependsOn 'prepareAssets'
}

tasks.named('jar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar.dependsOn copyDependencies
build.dependsOn copyDependencies
