buildscript {
    repositories {
        maven {
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            url = 'https://repo.spongepowered.org/maven'
        }
        mavenCentral()
    }

    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
    maven {
        url "https://cursemaven.com"
    }
}

apply plugin: 'net.minecraftforge.gradle'

apply plugin: 'eclipse'
apply plugin: 'maven-publish'

apply plugin: 'org.spongepowered.mixin'

// File metadata
version = '0.1'
group = 'org.imesense.emptymod.modid'
archivesBaseName = 'emptymod'

// Java version
sourceCompatibility =
targetCompatibility =
compileJava.sourceCompatibility =
compileJava.targetCompatibility =
    '1.8'

minecraft {
    // Mappings settings of Minecraft
    mappings channel: 'snapshot', version: '20171003-1.12'

    // Uncomment this to disable `Srg` named sources JAR by default
    //makeObfSourceJar = false

    //accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations
    runs {
        client {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            // Load LoadingPlugin class
            property 'fml.coreMods.load', 'org.imesense.emptymod.plugin.LoadingPlugin'

            // Enable mixins
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }

        server {
            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            // Load LoadingPlugin class
            property 'fml.coreMods.load', 'org.imesense.emptymod.plugin.LoadingPlugin'

            // Enable mixins
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }
    }
}

mixin {
    add sourceSets.main, 'mixins.emptymod.refmap.json'
}

dependencies {
    // Specify the version of Minecraft to use
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    // Optional dependencies that exist at compile-time but might not at runtime
    //provided 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // Dependencies to get remapped to current MCP mappings
    //deobf 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // SLF4J
    implementation 'org.slf4j:slf4j-simple:1.7.36'

    // Mixins
    implementation fg.deobf("curse.maven:mixin-0-7-0-8-compatibility-405327:3045381")
    implementation 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // GSON
    implementation 'com.google.code.gson:gson:2.8.9'

    // Byte Buddy
    implementation 'net.bytebuddy:byte-buddy:1.12.9'

    // DivineRPG
    //implementation fg.deobf("curse.maven:official-divinerpg-363543:2937175")
}

// Get properties into the manifest for reading by the runtime
jar {
    manifest {
        attributes([
            "Specification-Title": "emptymod",
            "Specification-Vendor": "imesense",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"imesense",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
            "MixinConfigs": "mixins.emptymod.json",
            "FMLCorePlugin": "org.imesense.emptymod.plugin.LoadingPlugin",
            "FMLCorePluginContainsFMLMod": "true",
            "ForceLoadAsMod": "true"
        ])
    }
}

// Preferred method to reobfuscate JAR file
jar.finalizedBy('reobfJar')

// Build sources task
tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    from sourceSets.main.resources
    classifier = 'sources'
}

// Build documentation task
tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    from "$buildDir/docs/javadoc"
    classifier = 'javadoc'
}

// Build additional artifacts
artifacts {
    archives sourcesJar
    archives javadocJar
}

// Delay the obfuscation
//publish.dependsOn('reobfJar')

// Set publish settings
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifact sourcesJar
            artifact javadocJar
        }
    }

    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// Enable packaging of metadata and resources
sourceSets {
    main {
        output.resourcesDir = output.classesDir
    }
}

// Enable annotations for mixins
compileJava {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs += [
        "-AdefaultObfuscationEnv=searge",
        "-AoutRefMap=mixins.emptymod.refmap.json"
    ]
}

task copyDependencies(type: Copy) {
    from configurations.runtimeClasspath.filter {
        it.name.contains("mixin-0-7-0-8-compatibility")
    }
    into 'build/libs'
}

build.dependsOn copyDependencies
