# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Build server"

on:
    push:
        branches:
            - "**"
        paths:
            - ".github/workflows/**"
            - "docker/**"
            - "gradle/**"
            - "src/**"
            - "*.gradle"
            - "gradle*"

    pull_request:
        branches:
            - "**"
        paths:
            - ".github/workflows/**"
            - "docker/**"
            - "gradle/**"
            - "src/**"
            - "*.gradle"
            - "gradle*"

defaults:
    run:
        shell: pwsh

jobs:
    build-image:
        name: "Build image"

        strategy:
            matrix:
                system:
                    - ubuntu-24.04

        runs-on: ${{ matrix.system }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set tag
              run: |
                  $tag = [math]::Round((New-TimeSpan -Start (Get-Date "1970-01-01") -End (Get-Date)).TotalSeconds)
                  Add-Content -Path $env:GITHUB_ENV -Value "tag=$tag"

            - name: Build image
              run: |
                  chmod +x docker/Server/build-server.sh
                  ./docker/Server/build-server.sh
                  docker tag `
                      ${{ github.event.repository.name }}:latest `
                      ${{ github.event.repository.name }}:${{ env.tag }}
                  docker save `
                      -o ${{ github.event.repository.name }}-${{ env.tag }}.tar `
                      ${{ github.event.repository.name }}:${{ env.tag }}

            - name: Upload image
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.repository.name }}-${{ github.sha }}
                  path: |
                      ${{ github.workspace }}/build/libs/
