# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Build modification"

on:
    push:
        branches:
            - "**"
        paths:
            - ".github/workflows/**"
            - "gradle/**"
            - "src/**"
            - "*.gradle"
            - "gradle*"

    pull_request:
        branches:
            - "**"
        paths:
            - ".github/workflows/**"
            - "gradle/**"
            - "src/**"
            - "*.gradle"
            - "gradle*"

defaults:
    run:
        shell: bash

jobs:
    build-modification:
        name: "Build modification"

        strategy:
            matrix:
                system:
                    - ubuntu-latest

        runs-on: ${{ matrix.system }}

        env:
            GRADLE_USER_HOME: ${{ github.workspace }}/.gradle/cache

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: Modification-${{ hashFiles('**/build.gradle') }}
                  restore-keys: |
                      Modification-${{ hashFiles('**/build.gradle') }}
                      Modification-
                  path: |
                      ${{ github.workspace }}/.gradle/cache
                  enableCrossOsArchive: true

            - name: Build modification
              run: |
                  ${{ github.workspace }}/gradlew build

            - name: Upload modification
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.repository.name }}-${{ github.sha }}
                  path: ${{ github.workspace }}/build/libs/
